GET http://localhost:{{httpPort}}/mt/0/1/2;3
Accept: application/json

###
POST http://localhost:{{httpPort}}/mget/0/1/2;3
Content-Type: application/json

{
  "eq": {
    "2": "1613508462904479744"
  }
}

###
POST http://localhost:{{httpPort}}/mt/0/1
Content-Type: application/json

{
  "id": "2",
  "valueMap": [
    {"3": "adadada"}
  ]
}

###
PUT http://localhost:{{httpPort}}/mt/0/1
Content-Type: application/json

{
  "condition": {
    "eq": {
      "2": "1618868532567740416"
    }
  },
  "valueMap": [
    {
      "3": "bbaaaaaaaaaaaaaaaa"
    }
  ]
}


###
DELETE http://localhost:{{httpPort}}/mt/0/1
Content-Type: application/json

{
  "eq": {
    "2": "1618868532567740416"
  }
}


###
GRPC localhost:{{grpcPort}}/mtCrud.MtCrud/GetData

{
  "order": null,
  "limit": "2",
  "cols": [
    "3"
  ],
  "eq":{
    "2": "1613503416280158208"
  },
  "gt": null,
  "lt": null,
  "like": null,
  "dbName": "0",
  "tbName": "1"
}

###
GRPC localhost:{{grpcPort}}/mtCrud.MtCrud/PostData

{
  "id": "2",
  "ct": "",
  "ut": "",
  "valueMap": {
    "3": "5"
  },
  "dbName": "0",
  "tbName": "1"
}
<> 2023-01-12T201025.OK.json

###
GRPC localhost:{{grpcPort}}/mtCrud.MtCrud/PutData

{
  "condition":{
    "eq":{
      "2":"1613508595301879808"
    },
    "gt":{
    },
    "lt":{
    },
    "like":{
    }
  },
  "valueMap":{
    "3":"132132"
  },
  "dbName": "0",
  "tbName": "1"
}

###
GRPC localhost:{{grpcPort}}/mtCrud.MtCrud/DelData

{
  "dbName": "0",
  "tbName": "1",
  "eq":{
    "2":"1613508595301879808"
  },
  "gt":{
  },
  "lt":{
  },
  "like":{
  }
}


###
GRPC localhost:{{grpcPort}}/mtCrud.MtCrud/ATDelData

{
  "dbName": "0",
  "tbName": "1",
  "eq":{
    "2":"1613503416280158208"
  }
}

###
GRPC localhost:{{grpcPort}}/mtCrud.MtCrud/ConfirmAT

{
  "ATId": "1612009362434428928"
}

###
GRPC localhost:{{grpcPort}}/mtCrud.MtCrud/RollbackAT

{
  "ATId": "1618869752908877824"
}


###
POST http://localhost:{{httpPort}}/a
Content-Type: application/json

{
  "id": "1613503416280158208"
}


###
POST http://localhost:{{httpPort}}/b
Content-Type: application/json

{
  "id": "1613503416280158208"
}
