// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtcrud.proto

package pers.mtx.grpc.mtcrud;

public interface ATTransactionIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mtCrud.ATTransactionId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 ATId = 1;</code>
   * @return The aTId.
   */
  long getATId();
}
