// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtcrud.proto

package pers.mtx.grpc.mtcrud;

/**
 * Protobuf type {@code mtCrud.GetParams}
 */
public final class GetParams extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mtCrud.GetParams)
    GetParamsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetParams.newBuilder() to construct.
  private GetParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetParams() {
    limit_ = "";
    cols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    dbName_ = "";
    tbName_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetParams();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return mtcrudProto.internal_static_mtCrud_GetParams_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetOrder();
      case 6:
        return internalGetEq();
      case 7:
        return internalGetGt();
      case 8:
        return internalGetLt();
      case 9:
        return internalGetLike();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return mtcrudProto.internal_static_mtCrud_GetParams_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GetParams.class, Builder.class);
  }

  public static final int ORDER_FIELD_NUMBER = 1;
  private static final class OrderDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, String> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, String>newDefaultInstance(
                mtcrudProto.internal_static_mtCrud_GetParams_OrderEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      String, String> order_;
  private com.google.protobuf.MapField<String, String>
  internalGetOrder() {
    if (order_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          OrderDefaultEntryHolder.defaultEntry);
    }
    return order_;
  }

  public int getOrderCount() {
    return internalGetOrder().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; order = 1;</code>
   */

  @Override
  public boolean containsOrder(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetOrder().getMap().containsKey(key);
  }
  /**
   * Use {@link #getOrderMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, String> getOrder() {
    return getOrderMap();
  }
  /**
   * <code>map&lt;string, string&gt; order = 1;</code>
   */
  @Override

  public java.util.Map<String, String> getOrderMap() {
    return internalGetOrder().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; order = 1;</code>
   */
  @Override

  public String getOrderOrDefault(
      String key,
      String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetOrder().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; order = 1;</code>
   */
  @Override

  public String getOrderOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetOrder().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int LIMIT_FIELD_NUMBER = 2;
  private volatile Object limit_;
  /**
   * <code>string limit = 2;</code>
   * @return The limit.
   */
  @Override
  public String getLimit() {
    Object ref = limit_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      limit_ = s;
      return s;
    }
  }
  /**
   * <code>string limit = 2;</code>
   * @return The bytes for limit.
   */
  @Override
  public com.google.protobuf.ByteString
      getLimitBytes() {
    Object ref = limit_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      limit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList cols_;
  /**
   * <code>repeated string cols = 3;</code>
   * @return A list containing the cols.
   */
  public com.google.protobuf.ProtocolStringList
      getColsList() {
    return cols_;
  }
  /**
   * <code>repeated string cols = 3;</code>
   * @return The count of cols.
   */
  public int getColsCount() {
    return cols_.size();
  }
  /**
   * <code>repeated string cols = 3;</code>
   * @param index The index of the element to return.
   * @return The cols at the given index.
   */
  public String getCols(int index) {
    return cols_.get(index);
  }
  /**
   * <code>repeated string cols = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the cols at the given index.
   */
  public com.google.protobuf.ByteString
      getColsBytes(int index) {
    return cols_.getByteString(index);
  }

  public static final int DBNAME_FIELD_NUMBER = 4;
  private volatile Object dbName_;
  /**
   * <code>string dbName = 4;</code>
   * @return The dbName.
   */
  @Override
  public String getDbName() {
    Object ref = dbName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dbName_ = s;
      return s;
    }
  }
  /**
   * <code>string dbName = 4;</code>
   * @return The bytes for dbName.
   */
  @Override
  public com.google.protobuf.ByteString
      getDbNameBytes() {
    Object ref = dbName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dbName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TBNAME_FIELD_NUMBER = 5;
  private volatile Object tbName_;
  /**
   * <code>string tbName = 5;</code>
   * @return The tbName.
   */
  @Override
  public String getTbName() {
    Object ref = tbName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tbName_ = s;
      return s;
    }
  }
  /**
   * <code>string tbName = 5;</code>
   * @return The bytes for tbName.
   */
  @Override
  public com.google.protobuf.ByteString
      getTbNameBytes() {
    Object ref = tbName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tbName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EQ_FIELD_NUMBER = 6;
  private static final class EqDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, String> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, String>newDefaultInstance(
                mtcrudProto.internal_static_mtCrud_GetParams_EqEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      String, String> eq_;
  private com.google.protobuf.MapField<String, String>
  internalGetEq() {
    if (eq_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          EqDefaultEntryHolder.defaultEntry);
    }
    return eq_;
  }

  public int getEqCount() {
    return internalGetEq().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; eq = 6;</code>
   */

  @Override
  public boolean containsEq(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetEq().getMap().containsKey(key);
  }
  /**
   * Use {@link #getEqMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, String> getEq() {
    return getEqMap();
  }
  /**
   * <code>map&lt;string, string&gt; eq = 6;</code>
   */
  @Override

  public java.util.Map<String, String> getEqMap() {
    return internalGetEq().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; eq = 6;</code>
   */
  @Override

  public String getEqOrDefault(
      String key,
      String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetEq().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; eq = 6;</code>
   */
  @Override

  public String getEqOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetEq().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int GT_FIELD_NUMBER = 7;
  private static final class GtDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, String> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, String>newDefaultInstance(
                mtcrudProto.internal_static_mtCrud_GetParams_GtEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      String, String> gt_;
  private com.google.protobuf.MapField<String, String>
  internalGetGt() {
    if (gt_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          GtDefaultEntryHolder.defaultEntry);
    }
    return gt_;
  }

  public int getGtCount() {
    return internalGetGt().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; gt = 7;</code>
   */

  @Override
  public boolean containsGt(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetGt().getMap().containsKey(key);
  }
  /**
   * Use {@link #getGtMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, String> getGt() {
    return getGtMap();
  }
  /**
   * <code>map&lt;string, string&gt; gt = 7;</code>
   */
  @Override

  public java.util.Map<String, String> getGtMap() {
    return internalGetGt().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; gt = 7;</code>
   */
  @Override

  public String getGtOrDefault(
      String key,
      String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetGt().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; gt = 7;</code>
   */
  @Override

  public String getGtOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetGt().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int LT_FIELD_NUMBER = 8;
  private static final class LtDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, String> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, String>newDefaultInstance(
                mtcrudProto.internal_static_mtCrud_GetParams_LtEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      String, String> lt_;
  private com.google.protobuf.MapField<String, String>
  internalGetLt() {
    if (lt_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          LtDefaultEntryHolder.defaultEntry);
    }
    return lt_;
  }

  public int getLtCount() {
    return internalGetLt().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; lt = 8;</code>
   */

  @Override
  public boolean containsLt(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetLt().getMap().containsKey(key);
  }
  /**
   * Use {@link #getLtMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, String> getLt() {
    return getLtMap();
  }
  /**
   * <code>map&lt;string, string&gt; lt = 8;</code>
   */
  @Override

  public java.util.Map<String, String> getLtMap() {
    return internalGetLt().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; lt = 8;</code>
   */
  @Override

  public String getLtOrDefault(
      String key,
      String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetLt().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; lt = 8;</code>
   */
  @Override

  public String getLtOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetLt().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int LIKE_FIELD_NUMBER = 9;
  private static final class LikeDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, String> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, String>newDefaultInstance(
                mtcrudProto.internal_static_mtCrud_GetParams_LikeEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      String, String> like_;
  private com.google.protobuf.MapField<String, String>
  internalGetLike() {
    if (like_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          LikeDefaultEntryHolder.defaultEntry);
    }
    return like_;
  }

  public int getLikeCount() {
    return internalGetLike().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; like = 9;</code>
   */

  @Override
  public boolean containsLike(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetLike().getMap().containsKey(key);
  }
  /**
   * Use {@link #getLikeMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, String> getLike() {
    return getLikeMap();
  }
  /**
   * <code>map&lt;string, string&gt; like = 9;</code>
   */
  @Override

  public java.util.Map<String, String> getLikeMap() {
    return internalGetLike().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; like = 9;</code>
   */
  @Override

  public String getLikeOrDefault(
      String key,
      String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetLike().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; like = 9;</code>
   */
  @Override

  public String getLikeOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetLike().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetOrder(),
        OrderDefaultEntryHolder.defaultEntry,
        1);
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(limit_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, limit_);
    }
    for (int i = 0; i < cols_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cols_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dbName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dbName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tbName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tbName_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetEq(),
        EqDefaultEntryHolder.defaultEntry,
        6);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetGt(),
        GtDefaultEntryHolder.defaultEntry,
        7);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetLt(),
        LtDefaultEntryHolder.defaultEntry,
        8);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetLike(),
        LikeDefaultEntryHolder.defaultEntry,
        9);
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<String, String> entry
         : internalGetOrder().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
      order__ = OrderDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, order__);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(limit_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, limit_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < cols_.size(); i++) {
        dataSize += computeStringSizeNoTag(cols_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getColsList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dbName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dbName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tbName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tbName_);
    }
    for (java.util.Map.Entry<String, String> entry
         : internalGetEq().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
      eq__ = EqDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, eq__);
    }
    for (java.util.Map.Entry<String, String> entry
         : internalGetGt().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
      gt__ = GtDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, gt__);
    }
    for (java.util.Map.Entry<String, String> entry
         : internalGetLt().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
      lt__ = LtDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, lt__);
    }
    for (java.util.Map.Entry<String, String> entry
         : internalGetLike().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
      like__ = LikeDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, like__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GetParams)) {
      return super.equals(obj);
    }
    GetParams other = (GetParams) obj;

    if (!internalGetOrder().equals(
        other.internalGetOrder())) return false;
    if (!getLimit()
        .equals(other.getLimit())) return false;
    if (!getColsList()
        .equals(other.getColsList())) return false;
    if (!getDbName()
        .equals(other.getDbName())) return false;
    if (!getTbName()
        .equals(other.getTbName())) return false;
    if (!internalGetEq().equals(
        other.internalGetEq())) return false;
    if (!internalGetGt().equals(
        other.internalGetGt())) return false;
    if (!internalGetLt().equals(
        other.internalGetLt())) return false;
    if (!internalGetLike().equals(
        other.internalGetLike())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetOrder().getMap().isEmpty()) {
      hash = (37 * hash) + ORDER_FIELD_NUMBER;
      hash = (53 * hash) + internalGetOrder().hashCode();
    }
    hash = (37 * hash) + LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getLimit().hashCode();
    if (getColsCount() > 0) {
      hash = (37 * hash) + COLS_FIELD_NUMBER;
      hash = (53 * hash) + getColsList().hashCode();
    }
    hash = (37 * hash) + DBNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDbName().hashCode();
    hash = (37 * hash) + TBNAME_FIELD_NUMBER;
    hash = (53 * hash) + getTbName().hashCode();
    if (!internalGetEq().getMap().isEmpty()) {
      hash = (37 * hash) + EQ_FIELD_NUMBER;
      hash = (53 * hash) + internalGetEq().hashCode();
    }
    if (!internalGetGt().getMap().isEmpty()) {
      hash = (37 * hash) + GT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetGt().hashCode();
    }
    if (!internalGetLt().getMap().isEmpty()) {
      hash = (37 * hash) + LT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetLt().hashCode();
    }
    if (!internalGetLike().getMap().isEmpty()) {
      hash = (37 * hash) + LIKE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetLike().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GetParams parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetParams parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetParams parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetParams parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetParams parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetParams parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetParams parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetParams parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetParams parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GetParams parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetParams parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetParams parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetParams prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mtCrud.GetParams}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mtCrud.GetParams)
      GetParamsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mtcrudProto.internal_static_mtCrud_GetParams_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetOrder();
        case 6:
          return internalGetEq();
        case 7:
          return internalGetGt();
        case 8:
          return internalGetLt();
        case 9:
          return internalGetLike();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableOrder();
        case 6:
          return internalGetMutableEq();
        case 7:
          return internalGetMutableGt();
        case 8:
          return internalGetMutableLt();
        case 9:
          return internalGetMutableLike();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mtcrudProto.internal_static_mtCrud_GetParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetParams.class, Builder.class);
    }

    // Construct using pers.mtx.grpc.mtcrud.GetParams.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      internalGetMutableOrder().clear();
      limit_ = "";

      cols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      dbName_ = "";

      tbName_ = "";

      internalGetMutableEq().clear();
      internalGetMutableGt().clear();
      internalGetMutableLt().clear();
      internalGetMutableLike().clear();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return mtcrudProto.internal_static_mtCrud_GetParams_descriptor;
    }

    @Override
    public GetParams getDefaultInstanceForType() {
      return GetParams.getDefaultInstance();
    }

    @Override
    public GetParams build() {
      GetParams result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public GetParams buildPartial() {
      GetParams result = new GetParams(this);
      int from_bitField0_ = bitField0_;
      result.order_ = internalGetOrder();
      result.order_.makeImmutable();
      result.limit_ = limit_;
      if (((bitField0_ & 0x00000002) != 0)) {
        cols_ = cols_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.cols_ = cols_;
      result.dbName_ = dbName_;
      result.tbName_ = tbName_;
      result.eq_ = internalGetEq();
      result.eq_.makeImmutable();
      result.gt_ = internalGetGt();
      result.gt_.makeImmutable();
      result.lt_ = internalGetLt();
      result.lt_.makeImmutable();
      result.like_ = internalGetLike();
      result.like_.makeImmutable();
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GetParams) {
        return mergeFrom((GetParams)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GetParams other) {
      if (other == GetParams.getDefaultInstance()) return this;
      internalGetMutableOrder().mergeFrom(
          other.internalGetOrder());
      if (!other.getLimit().isEmpty()) {
        limit_ = other.limit_;
        onChanged();
      }
      if (!other.cols_.isEmpty()) {
        if (cols_.isEmpty()) {
          cols_ = other.cols_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureColsIsMutable();
          cols_.addAll(other.cols_);
        }
        onChanged();
      }
      if (!other.getDbName().isEmpty()) {
        dbName_ = other.dbName_;
        onChanged();
      }
      if (!other.getTbName().isEmpty()) {
        tbName_ = other.tbName_;
        onChanged();
      }
      internalGetMutableEq().mergeFrom(
          other.internalGetEq());
      internalGetMutableGt().mergeFrom(
          other.internalGetGt());
      internalGetMutableLt().mergeFrom(
          other.internalGetLt());
      internalGetMutableLike().mergeFrom(
          other.internalGetLike());
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<String, String>
              order__ = input.readMessage(
                  OrderDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableOrder().getMutableMap().put(
                  order__.getKey(), order__.getValue());
              break;
            } // case 10
            case 18: {
              limit_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              String s = input.readStringRequireUtf8();
              ensureColsIsMutable();
              cols_.add(s);
              break;
            } // case 26
            case 34: {
              dbName_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              tbName_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              com.google.protobuf.MapEntry<String, String>
              eq__ = input.readMessage(
                  EqDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableEq().getMutableMap().put(
                  eq__.getKey(), eq__.getValue());
              break;
            } // case 50
            case 58: {
              com.google.protobuf.MapEntry<String, String>
              gt__ = input.readMessage(
                  GtDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableGt().getMutableMap().put(
                  gt__.getKey(), gt__.getValue());
              break;
            } // case 58
            case 66: {
              com.google.protobuf.MapEntry<String, String>
              lt__ = input.readMessage(
                  LtDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableLt().getMutableMap().put(
                  lt__.getKey(), lt__.getValue());
              break;
            } // case 66
            case 74: {
              com.google.protobuf.MapEntry<String, String>
              like__ = input.readMessage(
                  LikeDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableLike().getMutableMap().put(
                  like__.getKey(), like__.getValue());
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        String, String> order_;
    private com.google.protobuf.MapField<String, String>
    internalGetOrder() {
      if (order_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            OrderDefaultEntryHolder.defaultEntry);
      }
      return order_;
    }
    private com.google.protobuf.MapField<String, String>
    internalGetMutableOrder() {
      onChanged();;
      if (order_ == null) {
        order_ = com.google.protobuf.MapField.newMapField(
            OrderDefaultEntryHolder.defaultEntry);
      }
      if (!order_.isMutable()) {
        order_ = order_.copy();
      }
      return order_;
    }

    public int getOrderCount() {
      return internalGetOrder().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; order = 1;</code>
     */

    @Override
    public boolean containsOrder(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetOrder().getMap().containsKey(key);
    }
    /**
     * Use {@link #getOrderMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getOrder() {
      return getOrderMap();
    }
    /**
     * <code>map&lt;string, string&gt; order = 1;</code>
     */
    @Override

    public java.util.Map<String, String> getOrderMap() {
      return internalGetOrder().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; order = 1;</code>
     */
    @Override

    public String getOrderOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetOrder().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; order = 1;</code>
     */
    @Override

    public String getOrderOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetOrder().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearOrder() {
      internalGetMutableOrder().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; order = 1;</code>
     */

    public Builder removeOrder(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableOrder().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
    getMutableOrder() {
      return internalGetMutableOrder().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; order = 1;</code>
     */
    public Builder putOrder(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableOrder().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; order = 1;</code>
     */

    public Builder putAllOrder(
        java.util.Map<String, String> values) {
      internalGetMutableOrder().getMutableMap()
          .putAll(values);
      return this;
    }

    private Object limit_ = "";
    /**
     * <code>string limit = 2;</code>
     * @return The limit.
     */
    public String getLimit() {
      Object ref = limit_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        limit_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string limit = 2;</code>
     * @return The bytes for limit.
     */
    public com.google.protobuf.ByteString
        getLimitBytes() {
      Object ref = limit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        limit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string limit = 2;</code>
     * @param value The limit to set.
     * @return This builder for chaining.
     */
    public Builder setLimit(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      limit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string limit = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimit() {
      
      limit_ = getDefaultInstance().getLimit();
      onChanged();
      return this;
    }
    /**
     * <code>string limit = 2;</code>
     * @param value The bytes for limit to set.
     * @return This builder for chaining.
     */
    public Builder setLimitBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      limit_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList cols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureColsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        cols_ = new com.google.protobuf.LazyStringArrayList(cols_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string cols = 3;</code>
     * @return A list containing the cols.
     */
    public com.google.protobuf.ProtocolStringList
        getColsList() {
      return cols_.getUnmodifiableView();
    }
    /**
     * <code>repeated string cols = 3;</code>
     * @return The count of cols.
     */
    public int getColsCount() {
      return cols_.size();
    }
    /**
     * <code>repeated string cols = 3;</code>
     * @param index The index of the element to return.
     * @return The cols at the given index.
     */
    public String getCols(int index) {
      return cols_.get(index);
    }
    /**
     * <code>repeated string cols = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the cols at the given index.
     */
    public com.google.protobuf.ByteString
        getColsBytes(int index) {
      return cols_.getByteString(index);
    }
    /**
     * <code>repeated string cols = 3;</code>
     * @param index The index to set the value at.
     * @param value The cols to set.
     * @return This builder for chaining.
     */
    public Builder setCols(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureColsIsMutable();
      cols_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cols = 3;</code>
     * @param value The cols to add.
     * @return This builder for chaining.
     */
    public Builder addCols(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureColsIsMutable();
      cols_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cols = 3;</code>
     * @param values The cols to add.
     * @return This builder for chaining.
     */
    public Builder addAllCols(
        Iterable<String> values) {
      ensureColsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, cols_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cols = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCols() {
      cols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cols = 3;</code>
     * @param value The bytes of the cols to add.
     * @return This builder for chaining.
     */
    public Builder addColsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureColsIsMutable();
      cols_.add(value);
      onChanged();
      return this;
    }

    private Object dbName_ = "";
    /**
     * <code>string dbName = 4;</code>
     * @return The dbName.
     */
    public String getDbName() {
      Object ref = dbName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dbName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string dbName = 4;</code>
     * @return The bytes for dbName.
     */
    public com.google.protobuf.ByteString
        getDbNameBytes() {
      Object ref = dbName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dbName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dbName = 4;</code>
     * @param value The dbName to set.
     * @return This builder for chaining.
     */
    public Builder setDbName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dbName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dbName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDbName() {
      
      dbName_ = getDefaultInstance().getDbName();
      onChanged();
      return this;
    }
    /**
     * <code>string dbName = 4;</code>
     * @param value The bytes for dbName to set.
     * @return This builder for chaining.
     */
    public Builder setDbNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dbName_ = value;
      onChanged();
      return this;
    }

    private Object tbName_ = "";
    /**
     * <code>string tbName = 5;</code>
     * @return The tbName.
     */
    public String getTbName() {
      Object ref = tbName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tbName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string tbName = 5;</code>
     * @return The bytes for tbName.
     */
    public com.google.protobuf.ByteString
        getTbNameBytes() {
      Object ref = tbName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tbName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tbName = 5;</code>
     * @param value The tbName to set.
     * @return This builder for chaining.
     */
    public Builder setTbName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tbName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tbName = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTbName() {
      
      tbName_ = getDefaultInstance().getTbName();
      onChanged();
      return this;
    }
    /**
     * <code>string tbName = 5;</code>
     * @param value The bytes for tbName to set.
     * @return This builder for chaining.
     */
    public Builder setTbNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tbName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        String, String> eq_;
    private com.google.protobuf.MapField<String, String>
    internalGetEq() {
      if (eq_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EqDefaultEntryHolder.defaultEntry);
      }
      return eq_;
    }
    private com.google.protobuf.MapField<String, String>
    internalGetMutableEq() {
      onChanged();;
      if (eq_ == null) {
        eq_ = com.google.protobuf.MapField.newMapField(
            EqDefaultEntryHolder.defaultEntry);
      }
      if (!eq_.isMutable()) {
        eq_ = eq_.copy();
      }
      return eq_;
    }

    public int getEqCount() {
      return internalGetEq().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; eq = 6;</code>
     */

    @Override
    public boolean containsEq(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetEq().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEqMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getEq() {
      return getEqMap();
    }
    /**
     * <code>map&lt;string, string&gt; eq = 6;</code>
     */
    @Override

    public java.util.Map<String, String> getEqMap() {
      return internalGetEq().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; eq = 6;</code>
     */
    @Override

    public String getEqOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetEq().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; eq = 6;</code>
     */
    @Override

    public String getEqOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetEq().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearEq() {
      internalGetMutableEq().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; eq = 6;</code>
     */

    public Builder removeEq(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableEq().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
    getMutableEq() {
      return internalGetMutableEq().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; eq = 6;</code>
     */
    public Builder putEq(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableEq().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; eq = 6;</code>
     */

    public Builder putAllEq(
        java.util.Map<String, String> values) {
      internalGetMutableEq().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        String, String> gt_;
    private com.google.protobuf.MapField<String, String>
    internalGetGt() {
      if (gt_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            GtDefaultEntryHolder.defaultEntry);
      }
      return gt_;
    }
    private com.google.protobuf.MapField<String, String>
    internalGetMutableGt() {
      onChanged();;
      if (gt_ == null) {
        gt_ = com.google.protobuf.MapField.newMapField(
            GtDefaultEntryHolder.defaultEntry);
      }
      if (!gt_.isMutable()) {
        gt_ = gt_.copy();
      }
      return gt_;
    }

    public int getGtCount() {
      return internalGetGt().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; gt = 7;</code>
     */

    @Override
    public boolean containsGt(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetGt().getMap().containsKey(key);
    }
    /**
     * Use {@link #getGtMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getGt() {
      return getGtMap();
    }
    /**
     * <code>map&lt;string, string&gt; gt = 7;</code>
     */
    @Override

    public java.util.Map<String, String> getGtMap() {
      return internalGetGt().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; gt = 7;</code>
     */
    @Override

    public String getGtOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetGt().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; gt = 7;</code>
     */
    @Override

    public String getGtOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetGt().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearGt() {
      internalGetMutableGt().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; gt = 7;</code>
     */

    public Builder removeGt(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableGt().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
    getMutableGt() {
      return internalGetMutableGt().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; gt = 7;</code>
     */
    public Builder putGt(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableGt().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; gt = 7;</code>
     */

    public Builder putAllGt(
        java.util.Map<String, String> values) {
      internalGetMutableGt().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        String, String> lt_;
    private com.google.protobuf.MapField<String, String>
    internalGetLt() {
      if (lt_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            LtDefaultEntryHolder.defaultEntry);
      }
      return lt_;
    }
    private com.google.protobuf.MapField<String, String>
    internalGetMutableLt() {
      onChanged();;
      if (lt_ == null) {
        lt_ = com.google.protobuf.MapField.newMapField(
            LtDefaultEntryHolder.defaultEntry);
      }
      if (!lt_.isMutable()) {
        lt_ = lt_.copy();
      }
      return lt_;
    }

    public int getLtCount() {
      return internalGetLt().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; lt = 8;</code>
     */

    @Override
    public boolean containsLt(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetLt().getMap().containsKey(key);
    }
    /**
     * Use {@link #getLtMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getLt() {
      return getLtMap();
    }
    /**
     * <code>map&lt;string, string&gt; lt = 8;</code>
     */
    @Override

    public java.util.Map<String, String> getLtMap() {
      return internalGetLt().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; lt = 8;</code>
     */
    @Override

    public String getLtOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetLt().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; lt = 8;</code>
     */
    @Override

    public String getLtOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetLt().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearLt() {
      internalGetMutableLt().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; lt = 8;</code>
     */

    public Builder removeLt(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableLt().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
    getMutableLt() {
      return internalGetMutableLt().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; lt = 8;</code>
     */
    public Builder putLt(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableLt().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; lt = 8;</code>
     */

    public Builder putAllLt(
        java.util.Map<String, String> values) {
      internalGetMutableLt().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        String, String> like_;
    private com.google.protobuf.MapField<String, String>
    internalGetLike() {
      if (like_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            LikeDefaultEntryHolder.defaultEntry);
      }
      return like_;
    }
    private com.google.protobuf.MapField<String, String>
    internalGetMutableLike() {
      onChanged();;
      if (like_ == null) {
        like_ = com.google.protobuf.MapField.newMapField(
            LikeDefaultEntryHolder.defaultEntry);
      }
      if (!like_.isMutable()) {
        like_ = like_.copy();
      }
      return like_;
    }

    public int getLikeCount() {
      return internalGetLike().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; like = 9;</code>
     */

    @Override
    public boolean containsLike(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetLike().getMap().containsKey(key);
    }
    /**
     * Use {@link #getLikeMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getLike() {
      return getLikeMap();
    }
    /**
     * <code>map&lt;string, string&gt; like = 9;</code>
     */
    @Override

    public java.util.Map<String, String> getLikeMap() {
      return internalGetLike().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; like = 9;</code>
     */
    @Override

    public String getLikeOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetLike().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; like = 9;</code>
     */
    @Override

    public String getLikeOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetLike().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearLike() {
      internalGetMutableLike().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; like = 9;</code>
     */

    public Builder removeLike(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableLike().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
    getMutableLike() {
      return internalGetMutableLike().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; like = 9;</code>
     */
    public Builder putLike(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableLike().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; like = 9;</code>
     */

    public Builder putAllLike(
        java.util.Map<String, String> values) {
      internalGetMutableLike().getMutableMap()
          .putAll(values);
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mtCrud.GetParams)
  }

  // @@protoc_insertion_point(class_scope:mtCrud.GetParams)
  private static final GetParams DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetParams();
  }

  public static GetParams getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetParams>
      PARSER = new com.google.protobuf.AbstractParser<GetParams>() {
    @Override
    public GetParams parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetParams> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GetParams> getParserForType() {
    return PARSER;
  }

  @Override
  public GetParams getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

