// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtcrud.proto

package pers.mtx.grpc.mtcrud;

public interface GetParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mtCrud.GetParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; order = 1;</code>
   */
  int getOrderCount();
  /**
   * <code>map&lt;string, string&gt; order = 1;</code>
   */
  boolean containsOrder(
      String key);
  /**
   * Use {@link #getOrderMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getOrder();
  /**
   * <code>map&lt;string, string&gt; order = 1;</code>
   */
  java.util.Map<String, String>
  getOrderMap();
  /**
   * <code>map&lt;string, string&gt; order = 1;</code>
   */

  /* nullable */
String getOrderOrDefault(
      String key,
      /* nullable */
String defaultValue);
  /**
   * <code>map&lt;string, string&gt; order = 1;</code>
   */

  String getOrderOrThrow(
      String key);

  /**
   * <code>string limit = 2;</code>
   * @return The limit.
   */
  String getLimit();
  /**
   * <code>string limit = 2;</code>
   * @return The bytes for limit.
   */
  com.google.protobuf.ByteString
      getLimitBytes();

  /**
   * <code>repeated string cols = 3;</code>
   * @return A list containing the cols.
   */
  java.util.List<String>
      getColsList();
  /**
   * <code>repeated string cols = 3;</code>
   * @return The count of cols.
   */
  int getColsCount();
  /**
   * <code>repeated string cols = 3;</code>
   * @param index The index of the element to return.
   * @return The cols at the given index.
   */
  String getCols(int index);
  /**
   * <code>repeated string cols = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the cols at the given index.
   */
  com.google.protobuf.ByteString
      getColsBytes(int index);

  /**
   * <code>string dbName = 4;</code>
   * @return The dbName.
   */
  String getDbName();
  /**
   * <code>string dbName = 4;</code>
   * @return The bytes for dbName.
   */
  com.google.protobuf.ByteString
      getDbNameBytes();

  /**
   * <code>string tbName = 5;</code>
   * @return The tbName.
   */
  String getTbName();
  /**
   * <code>string tbName = 5;</code>
   * @return The bytes for tbName.
   */
  com.google.protobuf.ByteString
      getTbNameBytes();

  /**
   * <code>map&lt;string, string&gt; eq = 6;</code>
   */
  int getEqCount();
  /**
   * <code>map&lt;string, string&gt; eq = 6;</code>
   */
  boolean containsEq(
      String key);
  /**
   * Use {@link #getEqMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getEq();
  /**
   * <code>map&lt;string, string&gt; eq = 6;</code>
   */
  java.util.Map<String, String>
  getEqMap();
  /**
   * <code>map&lt;string, string&gt; eq = 6;</code>
   */

  /* nullable */
String getEqOrDefault(
      String key,
      /* nullable */
String defaultValue);
  /**
   * <code>map&lt;string, string&gt; eq = 6;</code>
   */

  String getEqOrThrow(
      String key);

  /**
   * <code>map&lt;string, string&gt; gt = 7;</code>
   */
  int getGtCount();
  /**
   * <code>map&lt;string, string&gt; gt = 7;</code>
   */
  boolean containsGt(
      String key);
  /**
   * Use {@link #getGtMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getGt();
  /**
   * <code>map&lt;string, string&gt; gt = 7;</code>
   */
  java.util.Map<String, String>
  getGtMap();
  /**
   * <code>map&lt;string, string&gt; gt = 7;</code>
   */

  /* nullable */
String getGtOrDefault(
      String key,
      /* nullable */
String defaultValue);
  /**
   * <code>map&lt;string, string&gt; gt = 7;</code>
   */

  String getGtOrThrow(
      String key);

  /**
   * <code>map&lt;string, string&gt; lt = 8;</code>
   */
  int getLtCount();
  /**
   * <code>map&lt;string, string&gt; lt = 8;</code>
   */
  boolean containsLt(
      String key);
  /**
   * Use {@link #getLtMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getLt();
  /**
   * <code>map&lt;string, string&gt; lt = 8;</code>
   */
  java.util.Map<String, String>
  getLtMap();
  /**
   * <code>map&lt;string, string&gt; lt = 8;</code>
   */

  /* nullable */
String getLtOrDefault(
      String key,
      /* nullable */
String defaultValue);
  /**
   * <code>map&lt;string, string&gt; lt = 8;</code>
   */

  String getLtOrThrow(
      String key);

  /**
   * <code>map&lt;string, string&gt; like = 9;</code>
   */
  int getLikeCount();
  /**
   * <code>map&lt;string, string&gt; like = 9;</code>
   */
  boolean containsLike(
      String key);
  /**
   * Use {@link #getLikeMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getLike();
  /**
   * <code>map&lt;string, string&gt; like = 9;</code>
   */
  java.util.Map<String, String>
  getLikeMap();
  /**
   * <code>map&lt;string, string&gt; like = 9;</code>
   */

  /* nullable */
String getLikeOrDefault(
      String key,
      /* nullable */
String defaultValue);
  /**
   * <code>map&lt;string, string&gt; like = 9;</code>
   */

  String getLikeOrThrow(
      String key);
}
