// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtcrud.proto

package pers.mtx.grpc.mtcrud;

public interface InfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mtCrud.Info)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string info = 1;</code>
   * @return The info.
   */
  String getInfo();
  /**
   * <code>string info = 1;</code>
   * @return The bytes for info.
   */
  com.google.protobuf.ByteString
      getInfoBytes();
}
