// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtcrud.proto

package pers.mtx.grpc.mtcrud;

public final class mtcrudProto {
  private mtcrudProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_Data_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_Data_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_Data_DataMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_Data_DataMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_ATTransactionId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_ATTransactionId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_Info_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_Info_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_GetParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_GetParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_GetParams_OrderEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_GetParams_OrderEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_GetParams_EqEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_GetParams_EqEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_GetParams_GtEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_GetParams_GtEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_GetParams_LtEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_GetParams_LtEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_GetParams_LikeEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_GetParams_LikeEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_PostParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_PostParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_PostParams_ValueMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_PostParams_ValueMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_PutParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_PutParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_PutParams_ValueMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_PutParams_ValueMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_DelParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_DelParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_DelParams_EqEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_DelParams_EqEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_DelParams_GtEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_DelParams_GtEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_DelParams_LtEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_DelParams_LtEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_DelParams_LikeEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_DelParams_LikeEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_Condition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_Condition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_Condition_EqEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_Condition_EqEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_Condition_GtEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_Condition_GtEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_Condition_LtEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_Condition_LtEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mtCrud_Condition_LikeEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mtCrud_Condition_LikeEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014mtcrud.proto\022\006mtCrud\"b\n\004Data\022*\n\007dataMa" +
      "p\030\001 \003(\0132\031.mtCrud.Data.DataMapEntry\032.\n\014Da" +
      "taMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\002" +
      "8\001\"\037\n\017ATTransactionId\022\014\n\004ATId\030\001 \001(\003\"\024\n\004I" +
      "nfo\022\014\n\004info\030\001 \001(\t\"\361\003\n\tGetParams\022+\n\005order" +
      "\030\001 \003(\0132\034.mtCrud.GetParams.OrderEntry\022\r\n\005" +
      "limit\030\002 \001(\t\022\014\n\004cols\030\003 \003(\t\022\016\n\006dbName\030\004 \001(" +
      "\t\022\016\n\006tbName\030\005 \001(\t\022%\n\002eq\030\006 \003(\0132\031.mtCrud.G" +
      "etParams.EqEntry\022%\n\002gt\030\007 \003(\0132\031.mtCrud.Ge" +
      "tParams.GtEntry\022%\n\002lt\030\010 \003(\0132\031.mtCrud.Get" +
      "Params.LtEntry\022)\n\004like\030\t \003(\0132\033.mtCrud.Ge" +
      "tParams.LikeEntry\032,\n\nOrderEntry\022\013\n\003key\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032)\n\007EqEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032)\n\007GtEntry\022\013\n" +
      "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032)\n\007LtEntry" +
      "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032+\n\tLike" +
      "Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\265\001" +
      "\n\nPostParams\022\n\n\002id\030\001 \001(\t\022\n\n\002ct\030\002 \001(\t\022\n\n\002" +
      "ut\030\003 \001(\t\022\016\n\006dbName\030\004 \001(\t\022\016\n\006tbName\030\005 \001(\t" +
      "\0222\n\010valueMap\030\006 \003(\0132 .mtCrud.PostParams.V" +
      "alueMapEntry\032/\n\rValueMapEntry\022\013\n\003key\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\265\001\n\tPutParams\022$\n\tc" +
      "ondition\030\001 \001(\0132\021.mtCrud.Condition\0221\n\010val" +
      "ueMap\030\002 \003(\0132\037.mtCrud.PutParams.ValueMapE" +
      "ntry\022\016\n\006dbName\030\003 \001(\t\022\016\n\006tbName\030\004 \001(\t\032/\n\r" +
      "ValueMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(" +
      "\t:\0028\001\"\371\002\n\tDelParams\022\016\n\006dbName\030\003 \001(\t\022\016\n\006t" +
      "bName\030\004 \001(\t\022%\n\002eq\030\006 \003(\0132\031.mtCrud.DelPara" +
      "ms.EqEntry\022%\n\002gt\030\007 \003(\0132\031.mtCrud.DelParam" +
      "s.GtEntry\022%\n\002lt\030\010 \003(\0132\031.mtCrud.DelParams" +
      ".LtEntry\022)\n\004like\030\t \003(\0132\033.mtCrud.DelParam" +
      "s.LikeEntry\032)\n\007EqEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005v" +
      "alue\030\002 \001(\t:\0028\001\032)\n\007GtEntry\022\013\n\003key\030\001 \001(\t\022\r" +
      "\n\005value\030\002 \001(\t:\0028\001\032)\n\007LtEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\t:\0028\001\032+\n\tLikeEntry\022\013\n\003key" +
      "\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\331\002\n\tCondition\022" +
      "%\n\002eq\030\001 \003(\0132\031.mtCrud.Condition.EqEntry\022%" +
      "\n\002gt\030\002 \003(\0132\031.mtCrud.Condition.GtEntry\022%\n" +
      "\002lt\030\003 \003(\0132\031.mtCrud.Condition.LtEntry\022)\n\004" +
      "like\030\004 \003(\0132\033.mtCrud.Condition.LikeEntry\032" +
      ")\n\007EqEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\002" +
      "8\001\032)\n\007GtEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(" +
      "\t:\0028\001\032)\n\007LtEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001\032+\n\tLikeEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t:\0028\0012\344\003\n\006MtCrud\022.\n\007GetData\022\021.mt" +
      "Crud.GetParams\032\014.mtCrud.Data\"\0000\001\022.\n\010Post" +
      "Data\022\022.mtCrud.PostParams\032\014.mtCrud.Info\"\000" +
      "\022,\n\007PutData\022\021.mtCrud.PutParams\032\014.mtCrud." +
      "Info\"\000\022,\n\007DelData\022\021.mtCrud.DelParams\032\014.m" +
      "tCrud.Info\"\000\0229\n\tATDelData\022\021.mtCrud.DelPa" +
      "rams\032\027.mtCrud.ATTransactionId\"\000\022;\n\nATPos" +
      "tData\022\022.mtCrud.PostParams\032\027.mtCrud.ATTra" +
      "nsactionId\"\000\0229\n\tATPutData\022\021.mtCrud.PutPa" +
      "rams\032\027.mtCrud.ATTransactionId\"\000\0224\n\tConfi" +
      "rmAT\022\027.mtCrud.ATTransactionId\032\014.mtCrud.I" +
      "nfo\"\000\0225\n\nRollbackAT\022\027.mtCrud.ATTransacti" +
      "onId\032\014.mtCrud.Info\"\000B+\n\024pers.mtx.grpc.mt" +
      "crudB\013mtcrudProtoP\001\242\002\003RTGb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mtCrud_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mtCrud_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_Data_descriptor,
        new String[] { "DataMap", });
    internal_static_mtCrud_Data_DataMapEntry_descriptor =
      internal_static_mtCrud_Data_descriptor.getNestedTypes().get(0);
    internal_static_mtCrud_Data_DataMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_Data_DataMapEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_mtCrud_ATTransactionId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mtCrud_ATTransactionId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_ATTransactionId_descriptor,
        new String[] { "ATId", });
    internal_static_mtCrud_Info_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mtCrud_Info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_Info_descriptor,
        new String[] { "Info", });
    internal_static_mtCrud_GetParams_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_mtCrud_GetParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_GetParams_descriptor,
        new String[] { "Order", "Limit", "Cols", "DbName", "TbName", "Eq", "Gt", "Lt", "Like", });
    internal_static_mtCrud_GetParams_OrderEntry_descriptor =
      internal_static_mtCrud_GetParams_descriptor.getNestedTypes().get(0);
    internal_static_mtCrud_GetParams_OrderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_GetParams_OrderEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_mtCrud_GetParams_EqEntry_descriptor =
      internal_static_mtCrud_GetParams_descriptor.getNestedTypes().get(1);
    internal_static_mtCrud_GetParams_EqEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_GetParams_EqEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_mtCrud_GetParams_GtEntry_descriptor =
      internal_static_mtCrud_GetParams_descriptor.getNestedTypes().get(2);
    internal_static_mtCrud_GetParams_GtEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_GetParams_GtEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_mtCrud_GetParams_LtEntry_descriptor =
      internal_static_mtCrud_GetParams_descriptor.getNestedTypes().get(3);
    internal_static_mtCrud_GetParams_LtEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_GetParams_LtEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_mtCrud_GetParams_LikeEntry_descriptor =
      internal_static_mtCrud_GetParams_descriptor.getNestedTypes().get(4);
    internal_static_mtCrud_GetParams_LikeEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_GetParams_LikeEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_mtCrud_PostParams_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_mtCrud_PostParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_PostParams_descriptor,
        new String[] { "Id", "Ct", "Ut", "DbName", "TbName", "ValueMap", });
    internal_static_mtCrud_PostParams_ValueMapEntry_descriptor =
      internal_static_mtCrud_PostParams_descriptor.getNestedTypes().get(0);
    internal_static_mtCrud_PostParams_ValueMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_PostParams_ValueMapEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_mtCrud_PutParams_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_mtCrud_PutParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_PutParams_descriptor,
        new String[] { "Condition", "ValueMap", "DbName", "TbName", });
    internal_static_mtCrud_PutParams_ValueMapEntry_descriptor =
      internal_static_mtCrud_PutParams_descriptor.getNestedTypes().get(0);
    internal_static_mtCrud_PutParams_ValueMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_PutParams_ValueMapEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_mtCrud_DelParams_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_mtCrud_DelParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_DelParams_descriptor,
        new String[] { "DbName", "TbName", "Eq", "Gt", "Lt", "Like", });
    internal_static_mtCrud_DelParams_EqEntry_descriptor =
      internal_static_mtCrud_DelParams_descriptor.getNestedTypes().get(0);
    internal_static_mtCrud_DelParams_EqEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_DelParams_EqEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_mtCrud_DelParams_GtEntry_descriptor =
      internal_static_mtCrud_DelParams_descriptor.getNestedTypes().get(1);
    internal_static_mtCrud_DelParams_GtEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_DelParams_GtEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_mtCrud_DelParams_LtEntry_descriptor =
      internal_static_mtCrud_DelParams_descriptor.getNestedTypes().get(2);
    internal_static_mtCrud_DelParams_LtEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_DelParams_LtEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_mtCrud_DelParams_LikeEntry_descriptor =
      internal_static_mtCrud_DelParams_descriptor.getNestedTypes().get(3);
    internal_static_mtCrud_DelParams_LikeEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_DelParams_LikeEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_mtCrud_Condition_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_mtCrud_Condition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_Condition_descriptor,
        new String[] { "Eq", "Gt", "Lt", "Like", });
    internal_static_mtCrud_Condition_EqEntry_descriptor =
      internal_static_mtCrud_Condition_descriptor.getNestedTypes().get(0);
    internal_static_mtCrud_Condition_EqEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_Condition_EqEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_mtCrud_Condition_GtEntry_descriptor =
      internal_static_mtCrud_Condition_descriptor.getNestedTypes().get(1);
    internal_static_mtCrud_Condition_GtEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_Condition_GtEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_mtCrud_Condition_LtEntry_descriptor =
      internal_static_mtCrud_Condition_descriptor.getNestedTypes().get(2);
    internal_static_mtCrud_Condition_LtEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_Condition_LtEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_mtCrud_Condition_LikeEntry_descriptor =
      internal_static_mtCrud_Condition_descriptor.getNestedTypes().get(3);
    internal_static_mtCrud_Condition_LikeEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mtCrud_Condition_LikeEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
