// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtcrud.proto

package pers.mtx.grpc.mtcrud;

/**
 * Protobuf type {@code mtCrud.PostParams}
 */
public final class PostParams extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mtCrud.PostParams)
    PostParamsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PostParams.newBuilder() to construct.
  private PostParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PostParams() {
    id_ = "";
    ct_ = "";
    ut_ = "";
    dbName_ = "";
    tbName_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new PostParams();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return mtcrudProto.internal_static_mtCrud_PostParams_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetValueMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return mtcrudProto.internal_static_mtCrud_PostParams_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PostParams.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @Override
  public String getId() {
    Object ref = id_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    Object ref = id_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CT_FIELD_NUMBER = 2;
  private volatile Object ct_;
  /**
   * <code>string ct = 2;</code>
   * @return The ct.
   */
  @Override
  public String getCt() {
    Object ref = ct_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ct_ = s;
      return s;
    }
  }
  /**
   * <code>string ct = 2;</code>
   * @return The bytes for ct.
   */
  @Override
  public com.google.protobuf.ByteString
      getCtBytes() {
    Object ref = ct_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ct_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UT_FIELD_NUMBER = 3;
  private volatile Object ut_;
  /**
   * <code>string ut = 3;</code>
   * @return The ut.
   */
  @Override
  public String getUt() {
    Object ref = ut_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ut_ = s;
      return s;
    }
  }
  /**
   * <code>string ut = 3;</code>
   * @return The bytes for ut.
   */
  @Override
  public com.google.protobuf.ByteString
      getUtBytes() {
    Object ref = ut_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ut_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DBNAME_FIELD_NUMBER = 4;
  private volatile Object dbName_;
  /**
   * <code>string dbName = 4;</code>
   * @return The dbName.
   */
  @Override
  public String getDbName() {
    Object ref = dbName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dbName_ = s;
      return s;
    }
  }
  /**
   * <code>string dbName = 4;</code>
   * @return The bytes for dbName.
   */
  @Override
  public com.google.protobuf.ByteString
      getDbNameBytes() {
    Object ref = dbName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dbName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TBNAME_FIELD_NUMBER = 5;
  private volatile Object tbName_;
  /**
   * <code>string tbName = 5;</code>
   * @return The tbName.
   */
  @Override
  public String getTbName() {
    Object ref = tbName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tbName_ = s;
      return s;
    }
  }
  /**
   * <code>string tbName = 5;</code>
   * @return The bytes for tbName.
   */
  @Override
  public com.google.protobuf.ByteString
      getTbNameBytes() {
    Object ref = tbName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tbName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUEMAP_FIELD_NUMBER = 6;
  private static final class ValueMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, String> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, String>newDefaultInstance(
                mtcrudProto.internal_static_mtCrud_PostParams_ValueMapEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      String, String> valueMap_;
  private com.google.protobuf.MapField<String, String>
  internalGetValueMap() {
    if (valueMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ValueMapDefaultEntryHolder.defaultEntry);
    }
    return valueMap_;
  }

  public int getValueMapCount() {
    return internalGetValueMap().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; valueMap = 6;</code>
   */

  @Override
  public boolean containsValueMap(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetValueMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getValueMapMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, String> getValueMap() {
    return getValueMapMap();
  }
  /**
   * <code>map&lt;string, string&gt; valueMap = 6;</code>
   */
  @Override

  public java.util.Map<String, String> getValueMapMap() {
    return internalGetValueMap().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; valueMap = 6;</code>
   */
  @Override

  public String getValueMapOrDefault(
      String key,
      String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetValueMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; valueMap = 6;</code>
   */
  @Override

  public String getValueMapOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetValueMap().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ct_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ct_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ut_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ut_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dbName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dbName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tbName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tbName_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetValueMap(),
        ValueMapDefaultEntryHolder.defaultEntry,
        6);
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ct_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ct_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ut_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ut_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dbName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dbName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tbName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tbName_);
    }
    for (java.util.Map.Entry<String, String> entry
         : internalGetValueMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
      valueMap__ = ValueMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, valueMap__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PostParams)) {
      return super.equals(obj);
    }
    PostParams other = (PostParams) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getCt()
        .equals(other.getCt())) return false;
    if (!getUt()
        .equals(other.getUt())) return false;
    if (!getDbName()
        .equals(other.getDbName())) return false;
    if (!getTbName()
        .equals(other.getTbName())) return false;
    if (!internalGetValueMap().equals(
        other.internalGetValueMap())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + CT_FIELD_NUMBER;
    hash = (53 * hash) + getCt().hashCode();
    hash = (37 * hash) + UT_FIELD_NUMBER;
    hash = (53 * hash) + getUt().hashCode();
    hash = (37 * hash) + DBNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDbName().hashCode();
    hash = (37 * hash) + TBNAME_FIELD_NUMBER;
    hash = (53 * hash) + getTbName().hashCode();
    if (!internalGetValueMap().getMap().isEmpty()) {
      hash = (37 * hash) + VALUEMAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetValueMap().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PostParams parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PostParams parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PostParams parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PostParams parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PostParams parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PostParams parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PostParams parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PostParams parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static PostParams parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static PostParams parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PostParams parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PostParams parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PostParams prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mtCrud.PostParams}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mtCrud.PostParams)
      PostParamsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mtcrudProto.internal_static_mtCrud_PostParams_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetValueMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableValueMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mtcrudProto.internal_static_mtCrud_PostParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PostParams.class, Builder.class);
    }

    // Construct using pers.mtx.grpc.mtcrud.PostParams.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = "";

      ct_ = "";

      ut_ = "";

      dbName_ = "";

      tbName_ = "";

      internalGetMutableValueMap().clear();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return mtcrudProto.internal_static_mtCrud_PostParams_descriptor;
    }

    @Override
    public PostParams getDefaultInstanceForType() {
      return PostParams.getDefaultInstance();
    }

    @Override
    public PostParams build() {
      PostParams result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public PostParams buildPartial() {
      PostParams result = new PostParams(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.ct_ = ct_;
      result.ut_ = ut_;
      result.dbName_ = dbName_;
      result.tbName_ = tbName_;
      result.valueMap_ = internalGetValueMap();
      result.valueMap_.makeImmutable();
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PostParams) {
        return mergeFrom((PostParams)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PostParams other) {
      if (other == PostParams.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getCt().isEmpty()) {
        ct_ = other.ct_;
        onChanged();
      }
      if (!other.getUt().isEmpty()) {
        ut_ = other.ut_;
        onChanged();
      }
      if (!other.getDbName().isEmpty()) {
        dbName_ = other.dbName_;
        onChanged();
      }
      if (!other.getTbName().isEmpty()) {
        tbName_ = other.tbName_;
        onChanged();
      }
      internalGetMutableValueMap().mergeFrom(
          other.internalGetValueMap());
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              ct_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              ut_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              dbName_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              tbName_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              com.google.protobuf.MapEntry<String, String>
              valueMap__ = input.readMessage(
                  ValueMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableValueMap().getMutableMap().put(
                  valueMap__.getKey(), valueMap__.getValue());
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public String getId() {
      Object ref = id_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private Object ct_ = "";
    /**
     * <code>string ct = 2;</code>
     * @return The ct.
     */
    public String getCt() {
      Object ref = ct_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ct_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string ct = 2;</code>
     * @return The bytes for ct.
     */
    public com.google.protobuf.ByteString
        getCtBytes() {
      Object ref = ct_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ct_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ct = 2;</code>
     * @param value The ct to set.
     * @return This builder for chaining.
     */
    public Builder setCt(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ct_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ct = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCt() {
      
      ct_ = getDefaultInstance().getCt();
      onChanged();
      return this;
    }
    /**
     * <code>string ct = 2;</code>
     * @param value The bytes for ct to set.
     * @return This builder for chaining.
     */
    public Builder setCtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ct_ = value;
      onChanged();
      return this;
    }

    private Object ut_ = "";
    /**
     * <code>string ut = 3;</code>
     * @return The ut.
     */
    public String getUt() {
      Object ref = ut_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ut_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string ut = 3;</code>
     * @return The bytes for ut.
     */
    public com.google.protobuf.ByteString
        getUtBytes() {
      Object ref = ut_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ut_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ut = 3;</code>
     * @param value The ut to set.
     * @return This builder for chaining.
     */
    public Builder setUt(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ut_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ut = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUt() {
      
      ut_ = getDefaultInstance().getUt();
      onChanged();
      return this;
    }
    /**
     * <code>string ut = 3;</code>
     * @param value The bytes for ut to set.
     * @return This builder for chaining.
     */
    public Builder setUtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ut_ = value;
      onChanged();
      return this;
    }

    private Object dbName_ = "";
    /**
     * <code>string dbName = 4;</code>
     * @return The dbName.
     */
    public String getDbName() {
      Object ref = dbName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dbName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string dbName = 4;</code>
     * @return The bytes for dbName.
     */
    public com.google.protobuf.ByteString
        getDbNameBytes() {
      Object ref = dbName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dbName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dbName = 4;</code>
     * @param value The dbName to set.
     * @return This builder for chaining.
     */
    public Builder setDbName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dbName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dbName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDbName() {
      
      dbName_ = getDefaultInstance().getDbName();
      onChanged();
      return this;
    }
    /**
     * <code>string dbName = 4;</code>
     * @param value The bytes for dbName to set.
     * @return This builder for chaining.
     */
    public Builder setDbNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dbName_ = value;
      onChanged();
      return this;
    }

    private Object tbName_ = "";
    /**
     * <code>string tbName = 5;</code>
     * @return The tbName.
     */
    public String getTbName() {
      Object ref = tbName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tbName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string tbName = 5;</code>
     * @return The bytes for tbName.
     */
    public com.google.protobuf.ByteString
        getTbNameBytes() {
      Object ref = tbName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tbName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tbName = 5;</code>
     * @param value The tbName to set.
     * @return This builder for chaining.
     */
    public Builder setTbName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tbName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tbName = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTbName() {
      
      tbName_ = getDefaultInstance().getTbName();
      onChanged();
      return this;
    }
    /**
     * <code>string tbName = 5;</code>
     * @param value The bytes for tbName to set.
     * @return This builder for chaining.
     */
    public Builder setTbNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tbName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        String, String> valueMap_;
    private com.google.protobuf.MapField<String, String>
    internalGetValueMap() {
      if (valueMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValueMapDefaultEntryHolder.defaultEntry);
      }
      return valueMap_;
    }
    private com.google.protobuf.MapField<String, String>
    internalGetMutableValueMap() {
      onChanged();;
      if (valueMap_ == null) {
        valueMap_ = com.google.protobuf.MapField.newMapField(
            ValueMapDefaultEntryHolder.defaultEntry);
      }
      if (!valueMap_.isMutable()) {
        valueMap_ = valueMap_.copy();
      }
      return valueMap_;
    }

    public int getValueMapCount() {
      return internalGetValueMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; valueMap = 6;</code>
     */

    @Override
    public boolean containsValueMap(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetValueMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValueMapMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getValueMap() {
      return getValueMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; valueMap = 6;</code>
     */
    @Override

    public java.util.Map<String, String> getValueMapMap() {
      return internalGetValueMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; valueMap = 6;</code>
     */
    @Override

    public String getValueMapOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetValueMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; valueMap = 6;</code>
     */
    @Override

    public String getValueMapOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetValueMap().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearValueMap() {
      internalGetMutableValueMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; valueMap = 6;</code>
     */

    public Builder removeValueMap(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableValueMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
    getMutableValueMap() {
      return internalGetMutableValueMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; valueMap = 6;</code>
     */
    public Builder putValueMap(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableValueMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; valueMap = 6;</code>
     */

    public Builder putAllValueMap(
        java.util.Map<String, String> values) {
      internalGetMutableValueMap().getMutableMap()
          .putAll(values);
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mtCrud.PostParams)
  }

  // @@protoc_insertion_point(class_scope:mtCrud.PostParams)
  private static final PostParams DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PostParams();
  }

  public static PostParams getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PostParams>
      PARSER = new com.google.protobuf.AbstractParser<PostParams>() {
    @Override
    public PostParams parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PostParams> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<PostParams> getParserForType() {
    return PARSER;
  }

  @Override
  public PostParams getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

