// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtcrud.proto

package pers.mtx.grpc.mtcrud;

public interface PutParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mtCrud.PutParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mtCrud.Condition condition = 1;</code>
   * @return Whether the condition field is set.
   */
  boolean hasCondition();
  /**
   * <code>.mtCrud.Condition condition = 1;</code>
   * @return The condition.
   */
  Condition getCondition();
  /**
   * <code>.mtCrud.Condition condition = 1;</code>
   */
  ConditionOrBuilder getConditionOrBuilder();

  /**
   * <code>map&lt;string, string&gt; valueMap = 2;</code>
   */
  int getValueMapCount();
  /**
   * <code>map&lt;string, string&gt; valueMap = 2;</code>
   */
  boolean containsValueMap(
      String key);
  /**
   * Use {@link #getValueMapMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getValueMap();
  /**
   * <code>map&lt;string, string&gt; valueMap = 2;</code>
   */
  java.util.Map<String, String>
  getValueMapMap();
  /**
   * <code>map&lt;string, string&gt; valueMap = 2;</code>
   */

  /* nullable */
String getValueMapOrDefault(
      String key,
      /* nullable */
String defaultValue);
  /**
   * <code>map&lt;string, string&gt; valueMap = 2;</code>
   */

  String getValueMapOrThrow(
      String key);

  /**
   * <code>string dbName = 3;</code>
   * @return The dbName.
   */
  String getDbName();
  /**
   * <code>string dbName = 3;</code>
   * @return The bytes for dbName.
   */
  com.google.protobuf.ByteString
      getDbNameBytes();

  /**
   * <code>string tbName = 4;</code>
   * @return The tbName.
   */
  String getTbName();
  /**
   * <code>string tbName = 4;</code>
   * @return The bytes for tbName.
   */
  com.google.protobuf.ByteString
      getTbNameBytes();
}
